### ISSUE TITLE
Enable/Disable Option depending on Result?

### ISSUE THREAD

**Issue by schwarmco** [Ashvin-Pal/jest-console-group-reporter#36]
I'd love to use this library but right now my use case isn't possible. I'm running `jest --watch` and want to show console messages only for failing tests (with the afterEach summary).

Having some sort of result-aware option here
https://github.com/Ashvin-Pal/jest-console-group-reporter/blob/ccddf68a36b43b09b948dbd14fd20b631ca00bfd/src/JestConsoleGroupReporter.ts#L72-L77
would be awesome!

**Comment by Ashvin-Pal** [comment]
Hey @schwarmco,

Let me check it out and get back to you!

**Comment by Ashvin-Pal** [comment]
@schwarmco Unfortunately, due to how Jest works, displaying console messages exclusively for failing tests is not possible. However, displaying messages for failing test suites is possible. Please let me know if you're interested, and I'll create a pull request.

**Comment by schwarmco** [comment]
Hi @Ashvin-Pal - yes, that's the way i currently have it set up (and also makes the most sense, i guess).
I have it like this:

```js
printTestFileHeader (testPath, config, result) {
    if (result.numFailingTests === 0 && !result.testExecError) {
        result.console = false
    }

    super.printTestFileHeader(testPath, config, result)
}
```

**Comment by Ashvin-Pal** [comment]
@schwarmco I've added the feature you requested. You can find the documentation over here https://github.com/Ashvin-Pal/jest-console-group-reporter?tab=readme-ov-file#onlyFailingTestSuites

Give us a star if you like the project 😄
